#!/bin/bash
# MonoKickstart Shell Script
# Written by Ethan "flibitijibibo" Lee

# Move to script's directory
cd "`dirname "$0"`"

# Get the system architecture
UNAME=`uname`
ARCH=`uname -m`
BASENAME=`basename "$0"`

# MonoKickstart picks the right libfolder, so just execute the right binary.
if [ "$UNAME" == "Darwin" ]; then
	ext=osx
else
	ext=x86_64
fi


export MONO_IOMAP=all
./${BASENAME}.bin.${ext} $@

